name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      continue-on-error: true

    - name: Cache JUCE
      id: check-juce-cache
      uses: actions/cache@v3
      with:
        path: JUCE
        key: ${{ runner.os }}-juce-7.0.5
      continue-on-error: true

    - name: Download JUCE
      if: steps.check-juce-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          curl -LO https://github.com/juce-framework/JUCE/releases/download/7.0.5/juce-7.0.5-osx.zip
          unzip juce-7.0.5-osx.zip
        else
          curl -LO https://github.com/juce-framework/JUCE/releases/download/7.0.5/juce-7.0.5-windows.zip
          unzip juce-7.0.5-windows.zip
        fi
      continue-on-error: true
      
    - name: Cache FRUT directory
      id: cache-frut
      uses: actions/cache@v3
      with:
        path: FRUT/build
        key: ${{ runner.os }}-frut-${{ hashFiles('FRUT/build') }}
      continue-on-error: true

    - name: Clone FRUT
      if: steps.cache-frut.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/McMartin/FRUT.git
      continue-on-error: true

    - name: Generate CMakeLists.txt
      if: steps.cache-frut.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Generate CMakeLists.txt"
        cd FRUT/build
        ../prefix/FRUT/bin/Jucer2CMake reprojucer ../"DR Filter.jucer" ../prefix/FRUT/cmake/Reprojucer.cmake
        cd ../..
        pwd
      continue-on-error: true

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      continue-on-error: true

    - name: Build DR Filter
      shell: bash
      run: |
        echo "Build DR Filter"
        cd "DR Filter"
        mkdir build && cd build
        cmake .. -G Ninja
        cmake --build .
        cd ../..
        pwd
      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DR-Filter-Binaries
        path: DR Filter/build
      continue-on-error: true

    - name: Cleanup
      if: always()
      run: |
        echo "Cleanup"
        rm -rf FRUT
        rm -rf JUCE
        rm -rf "DR Filter/build
