name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Cache JUCE
      id: check-juce-cache
      uses: actions/cache@v3
      with:
        path: JUCE
        key: ${{ runner.os }}-juce-7.0.5

    - name: Download JUCE
      if: steps.check-juce-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir JUCE
        cd JUCE
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          curl -LO https://github.com/juce-framework/JUCE/releases/download/7.0.5/juce-7.0.5-osx.zip
          unzip juce-7.0.5-osx.zip
        else
          curl -LO https://github.com/juce-framework/JUCE/releases/download/7.0.5/juce-7.0.5-windows.zip
          unzip juce-7.0.5-windows.zip
        fi
      
    - name: Cache FRUT directory
      id: cache-frut
      uses: actions/cache@v3
      with:
        path: FRUT/build
        key: ${{ runner.os }}-frut-${{ hashFiles('FRUT/build') }}

    - name: Clone FRUT
      if: steps.cache-frut.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/McMartin/FRUT.git

    - name: Generate CMakeLists.txt
      if: steps.cache-frut.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd FRUT
        mkdir build && cd build
        pwd
        echo "Generating CMakeLists.txt"
        cmake .. -DCMAKE_INSTALL_PREFIX="../DR-Filter" -DJUCE_ROOT="../../JUCE"
        cmake --build . --target install
        pwd
        echo "CMakeLists.txt Generated"
        ls
      
    - name: Build
      shell: bash
      run: |
        pwd
        echo "Converting the Jucer project to CMakeLists.txt"
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          ./FRUT/prefix/DR-Filter/bin/Jucer2Reprojucer ../"DR-Filter/DR-Filter/DR Filter.jucer" ./FRUT/cmake/Reprojucer.cmake
        else
          ./FRUT/prefix/DR-Filter/bin/Jucer2Reprojucer "..\\DR-Filter\\DR-Filter\\DR Filter.jucer" ".\\FRUT\\cmake\\Reprojucer.cmake"
        fi

        mkdir build
        cd build
        pwd
        echo "Building the project"
        
        # Build the project using CMake
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          cmake ..
          cmake --build .
        else
          cmake .. -G"Visual Studio 16 2019" -A x64
          cmake --build . --config Release
        fi
        echo "Build complete"

